#pytest.ini se crea en un archivo para utilizar los decoradores (markers) personalizados

[pytest]
markers = markersPersonalizado     #Estos marks sirven para personalizar, en el archivo test_operaciones se llama al markers personalizado
                                   # Si quiero ejecutar el makers personalizado en consola se llama : pytest -v -m markersPersonalizado